import type { PixelMap } from "./pixel";
import { layer } from "./pixel";

/**
 * Roles: K outline · W wood · w wood dark · N stone · n stone dark · R roof ·
 * r roof dark · C cloth/plaster · G gold · g gold dark · F fire · f fire bright ·
 * L leaf · l leaf dark · D dirt · d dirt dark · Y wheat · y wheat bright ·
 * P grape · T trim(violet) · S sand
 */

const SOIL: PixelMap = [
  "DDDDDDDDDDDDDDDD",
  "DdddDdddDdddDddD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DdddDdddDdddDddD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DdddDdddDdddDddD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DdddDdddDdddDddD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DdddDdddDdddDddD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
];

const SPROUT: PixelMap = [
  "................",
  "................",
  "..L...L...L...L.",
  ".LlL.LlL.LlL.LlL",
  "................",
  "................",
  "..L...L...L...L.",
  ".LlL.LlL.LlL.LlL",
  "................",
  "................",
  "..L...L...L...L.",
  ".LlL.LlL.LlL.LlL",
  "................",
  "................",
  "..L...L...L...L.",
  ".LlL.LlL.LlL.LlL",
];

const GROWING: PixelMap = [
  "..L...L...L...L.",
  "..L...L...L...L.",
  ".LLL.LLL.LLL.LLL",
  ".LlL.LlL.LlL.LlL",
  "..l...l...l...l.",
  "..L...L...L...L.",
  ".LLL.LLL.LLL.LLL",
  ".LlL.LlL.LlL.LlL",
  "..l...l...l...l.",
  "..L...L...L...L.",
  ".LLL.LLL.LLL.LLL",
  ".LlL.LlL.LlL.LlL",
  "..l...l...l...l.",
  "..L...L...L...L.",
  ".LLL.LLL.LLL.LLL",
  ".LlL.LlL.LlL.LlL",
];

const WHEAT_READY: PixelMap = [
  "..y...y...y...y.",
  ".yYy.yYy.yYy.yYy",
  ".YYY.YYY.YYY.YYY",
  "..Y...Y...Y...Y.",
  "..l...l...l...l.",
  "..y...y...y...y.",
  ".yYy.yYy.yYy.yYy",
  ".YYY.YYY.YYY.YYY",
  "..Y...Y...Y...Y.",
  "..l...l...l...l.",
  "..y...y...y...y.",
  ".yYy.yYy.yYy.yYy",
  ".YYY.YYY.YYY.YYY",
  "..Y...Y...Y...Y.",
  "..l...l...l...l.",
  "..l...l...l...l.",
];

export const FARM: PixelMap[] = [
  SOIL,
  layer(SOIL, SPROUT),
  layer(SOIL, GROWING),
  layer(SOIL, WHEAT_READY),
];

const TRELLIS: PixelMap = [
  ".W............W.",
  ".W............W.",
  ".WwwwwwwwwwwwwW.",
  ".W............W.",
  ".W............W.",
  ".W............W.",
  ".WwwwwwwwwwwwwW.",
  ".W............W.",
  ".W............W.",
  ".W............W.",
  ".WwwwwwwwwwwwwW.",
  ".W............W.",
  ".W............W.",
  ".W............W.",
  ".W............W.",
  ".W............W.",
];

const VINES: PixelMap = [
  "................",
  "..LL.LL..LL.LL..",
  ".LLLLLLLLLLLLLL.",
  "..lL.Ll..lL.Ll..",
  "................",
  "..LL.LL..LL.LL..",
  ".LLLLLLLLLLLLLL.",
  "..lL.Ll..lL.Ll..",
  "................",
  "..LL.LL..LL.LL..",
  ".LLLLLLLLLLLLLL.",
  "..lL.Ll..lL.Ll..",
  "................",
  "................",
  "................",
  "................",
];

const GRAPES: PixelMap = [
  "................",
  "................",
  "................",
  "..PP.PP..PP.PP..",
  "..PP..P..P..PP..",
  "................",
  "................",
  "..PP.PP..PP.PP..",
  "..PP..P..P..PP..",
  "................",
  "................",
  "..PP.PP..PP.PP..",
  "..PP..P..P..PP..",
  "................",
  "................",
  "................",
];

export const VINEYARD: PixelMap[] = [
  layer(SOIL, TRELLIS),
  layer(SOIL, TRELLIS, VINES.map((r, i) => (i > 7 ? ".".repeat(16) : r))),
  layer(SOIL, TRELLIS, VINES),
  layer(SOIL, TRELLIS, VINES, GRAPES),
];

const FLAX_FLOWER: PixelMap = [
  "..T...T...T...T.",
  ".T.T.T.T.T.T.T.T",
  "..T...T...T...T.",
  "..L...L...L...L.",
  "..T...T...T...T.",
  ".T.T.T.T.T.T.T.T",
  "..T...T...T...T.",
  "..L...L...L...L.",
  "..T...T...T...T.",
  ".T.T.T.T.T.T.T.T",
  "..T...T...T...T.",
  "..L...L...L...L.",
  "..T...T...T...T.",
  ".T.T.T.T.T.T.T.T",
  "..T...T...T...T.",
  "..L...L...L...L.",
];

export const FLAX: PixelMap[] = [
  SOIL,
  layer(SOIL, SPROUT),
  layer(SOIL, GROWING),
  layer(SOIL, FLAX_FLOWER),
];

const OLIVE_TREE: PixelMap = [
  "....LLLLLLLL....",
  "...LLlLLLLlLL...",
  "..LLLLOOLLLLLL..",
  "..LlLLOOLLlLLL..",
  "...LLLLLLLLLL...",
  "....LLLwLLL.....",
  "......www.......",
  "......wWw.......",
  "....LLLLLLLL....",
  "...LLOOLLOOLL...",
  "..LLLLOOLLLLLL..",
  "..LlLLLLLLLlLL..",
  "...LLLLLLLLLL...",
  ".....LLwLL......",
  "......www.......",
  "......wWw.......",
];

const OLIVE_FRUIT: PixelMap = [
  "................",
  "................",
  ".....OO..OO.....",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "....OO....OO....",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

export const GROVE: PixelMap[] = [
  layer(SOIL, OLIVE_TREE.map((r, i) => (i > 6 ? r : ".".repeat(16)))),
  layer(SOIL, OLIVE_TREE.map((r, i) => (i < 4 ? ".".repeat(16) : r))),
  layer(SOIL, OLIVE_TREE),
  layer(SOIL, OLIVE_TREE, OLIVE_FRUIT),
];

/** 32×32 mud-brick house, 2×2 tiles, origin bottom. */
export const HOUSE: PixelMap = [
  "..............KKKK..............",
  "............KKRRRRKK............",
  "..........KKRRRRRRRRKK..........",
  "........KKRRRRRRRRRRRRKK........",
  "......KKRRRRRRrRRRRRRRRRKK......",
  "....KKRRRRRRRrrRRRRRRRRRRRKK....",
  "..KKRRRRRRRRRrrRRRRRRRRRRRRRKK..",
  ".KRRRRRRRRRRrrrRRRRRRRRRRRRRRRK.",
  ".KrrrrrrrrrrrrrrrrrrrrrrrrrrrrK.",
  ".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
  "..KCCCCCCCCCCCCCCCCCCCCCCCCCCK..",
  "..KCCCCCCCCCCCCCCCCCCCCCCCCCCK..",
  "..KCCCKKKKCCCCCCCCCCCCKKKKCCCK..",
  "..KCCCKwwKCCCCCCCCCCCCKwwKCCCK..",
  "..KCCCKwwKCCCCCCCCCCCCKwwKCCCK..",
  "..KCCCKKKKCCCCCCCCCCCCKKKKCCCK..",
  "..KCCCCCCCCCCCCCCCCCCCCCCCCCCK..",
  "..KCCCCCCCCCCCCKKKKKKCCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWwWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KCCCCCCCCCCCKWWWWWWKCCCCCCCK..",
  "..KnnnnnnnnnnnKWWWWWWKnnnnnnnK..",
  "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const WELL: PixelMap = [
  "......KKKK......",
  ".....KwwwwK.....",
  "....KwwwwwwK....",
  "...KwwwwwwwwK...",
  "...KKKKKKKKKK...",
  "....W......W....",
  "....W..KK..W....",
  "....W.KwwK.W....",
  "..KKKKKKKKKKKK..",
  ".KNNnNNNNNNnNNK.",
  ".KNNNNKKKKNNNNK.",
  ".KnNNKKKKKKNNnK.",
  ".KNNNKKKKKKNNNK.",
  ".KNnNNKKKKNNnNK.",
  ".KNNNNNNNNNNNNK.",
  "..KKKKKKKKKKKK..",
];

export const WALL: PixelMap = [
  "KKKKKKKKKKKKKKKK",
  "KNNNNNNNKNNNNNNK",
  "KNNNNNNNKNNNNNNK",
  "KnnnnnnnKnnnnnnK",
  "KKKKKKKKKKKKKKKK",
  "KNNNKNNNNNNNKNNK",
  "KNNNKNNNNNNNKNNK",
  "KnnnKnnnnnnnKnnK",
  "KKKKKKKKKKKKKKKK",
  "KNNNNNNNKNNNNNNK",
  "KNNNNNNNKNNNNNNK",
  "KnnnnnnnKnnnnnnK",
  "KKKKKKKKKKKKKKKK",
  "KNNNKNNNNNNNKNNK",
  "KnnnKnnnnnnnKnnK",
  "KKKKKKKKKKKKKKKK",
];

/** 16×32 watchtower, origin bottom. */
export const TOWER: PixelMap = [
  "....K......K....",
  "....KTT....K....",
  "....KTTT...K....",
  "....KT.....K....",
  "..KKKKKKKKKKKK..",
  "..KWWWWWWWWWWK..",
  "..KWwWWwWWwWWK..",
  "..KKKKKKKKKKKK..",
  "...KWWWWWWWWK...",
  "...KWWWWWWWWK...",
  "...KKKKKKKKKK...",
  "....KNNNNNNK....",
  "....KNnNNnNK....",
  "....KNNNNNNK....",
  "....KNNKKNNK....",
  "....KNNKKNNK....",
  "....KNnNNnNK....",
  "....KNNNNNNK....",
  "....KNNNNNNK....",
  "....KNnNNnNK....",
  "....KNNNNNNK....",
  "....KNNKKNNK....",
  "....KNNKKNNK....",
  "....KNnNNnNK....",
  "....KNNNNNNK....",
  "...KNNNNNNNNK...",
  "...KNnNNNNnNK...",
  "...KNNNNNNNNK...",
  "...KKKKKKKKKK...",
  "................",
  "................",
  "................",
];

/** 32×32 storehouse — sacks under a timber roof. */
export const STORE: PixelMap = [
  "..............KKKK..............",
  "............KKWWWWKK............",
  "..........KKWWWWWWWWKK..........",
  "........KKWWWWWWWWWWWWKK........",
  "......KKWWWWWWWWWWWWWWWWKK......",
  "....KKWWWWWWWWWWWWWWWWWWWWKK....",
  "...KWWWWWWWWWWWWWWWWWWWWWWWWK...",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "....KCCCCCCCCCCCCCCCCCCCCCCK....",
  "....KCCYYYYCCPPPPCCYYYYCCCCK....",
  "....KCYYYYYCPPPPPPCCYYYYYCCK....",
  "....KCYYYYYCPPPPPPCCYYYYYCCK....",
  "....KCCYYYYCCPPPPCCYYYYCCCCK....",
  "....KCCCCCCCCCCCCCCCCCCCCCCK....",
  "....KCCCCCCCCKKKKCCCCCCCCCCK....",
  "....KCCCCCCCCKWWKCCCCCCCCCCK....",
  "....KCCCCCCCCKWWKCCCCCCCCCCK....",
  "....KCCCCCCCCKKKKCCCCCCCCCCK....",
  "....KCCCCCCCCCCCCCCCCCCCCCCK....",
  "....KnnnnnnnnnnnnnnnnnnnnnnK....",
  "....KKKKKKKKKKKKKKKKKKKKKKKK....",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** 16×16 money changer — a gold-scale stall. */
export const CHANGER: PixelMap = [
  "KKKKKKKKKKKKKKKK",
  "KGCGCGCGCGCGCGCK",
  "KGCGCGCGCGCGCGCK",
  "KKKKKKKKKKKKKKKK",
  ".W....GGGG....W.",
  ".W...GGggGG...W.",
  ".W..GGKKKKGG..W.",
  ".W.GG......GG.W.",
  ".KKKKKKKKKKKKKK.",
  ".KWWWWWWWWWWWWK.",
  ".KWwWWWWWWWWwWK.",
  ".KWWWWWWWWWWWWK.",
  ".KKKKKKKKKKKKKK.",
  "..W..........W..",
  "..W..........W..",
  "..w..........w..",
];

/** 32×32 town hall — columns, steps, a gold lintel. */
export const HALL: PixelMap = [
  "..............KKKK..............",
  "............KKRRRRKK............",
  "..........KKRRRRRRRRKK..........",
  "........KKRRRRRRRRRRRRKK........",
  "......KKRRRRRRRRRRRRRRRRKK......",
  "....KKRRRRRRRRRRRRRRRRRRRRKK....",
  "...KRRRRRRRRRRRRRRRRRRRRRRRRK...",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "....KNGGGGGGGGGGGGGGGGGGGGNK....",
  "....KNGCCCCCCCCCCCCCCCCCCGNK....",
  "....KNCCCCCCCCCCCCCCCCCCCCNK....",
  "....KNCCKK...........KKCCCNK....",
  "....KNCCKK...........KKCCCNK....",
  "....KNCCKK...GGGGG...KKCCCNK....",
  "....KNCCKK...GgggG...KKCCCNK....",
  "....KNCCKK...........KKCCCNK....",
  "....KNCCKK...........KKCCCNK....",
  "....KNCCKK...........KKCCCNK....",
  "....KNNNNNNNNNNNNNNNNNNNNNNK....",
  "....KKKKKKKKKKKKKKKKKKKKKKKK....",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** 32×32 sheepfold — rail fence, gate, and a ewe, origin bottom. */
export const FOLD: PixelMap = [
  "................................",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "W..............................W",
  "W..........CCCCCCCC............W",
  "W.........CCcCCCCCCC...........W",
  "W.........CCCCCCCCCC...........W",
  "W........KKCCCCCCCCKK..........W",
  "W........KCCCCCCCCCCK..........W",
  "W.........KKK....KKK...........W",
  "W..........K......K............W",
  "W......DDDDDDDDDDDDDDDD........W",
  "W.....DddddddddddddddddD.......W",
  "W.....DDDDDDDDDDDDDDDDDD.......W",
  "W..............................W",
  "W..............................W",
  "W..............WW..............W",
  "WWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWW",
  "W.W.W.W.W.W.W.W...W.W.W.W.W.W.W.",
  "WWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWW",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const MARKET: PixelMap = [
  "KKKKKKKKKKKKKKKK",
  "KRCRCRCRCRCRCRCK",
  "KRCRCRCRCRCRCRCK",
  "KKKKKKKKKKKKKKKK",
  ".W............W.",
  ".W............W.",
  ".W..Y.PP..Y...W.",
  ".W.YYY.PP.YY..W.",
  ".KKKKKKKKKKKKKK.",
  ".KWWWWWWWWWWWWK.",
  ".KWwWWWWWWWWwWK.",
  ".KWWWWWWWWWWWWK.",
  ".KKKKKKKKKKKKKK.",
  "..W..........W..",
  "..W..........W..",
  "..w..........w..",
];

/** 16×24 lamp post, origin bottom. */
export const LAMP: PixelMap = [
  "......KKKK......",
  ".....KGGGGK.....",
  ".....KGffGK.....",
  ".....KGfFGK.....",
  ".....KGFFGK.....",
  ".....KGGGGK.....",
  "......KKKK......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".......ww.......",
  ".....KKwwKK.....",
  "....KnnnnnnK....",
  "....KKKKKKKK....",
  "................",
];

/** 32×32 altar, origin bottom. Levels add canopy, pillars, gold, bigger flame. */
const ALTAR_BASE: PixelMap = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............ff................",
  ".............fFFf...............",
  ".............FFFF...............",
  "............KFFFFK..............",
  "............KFFFFK..............",
  "...........KKKKKKKK.............",
  "..........KNNNNNNNNK............",
  "..........KNnNNNNnNK............",
  "..........KNNNNNNNNK............",
  ".........KKNNNNNNNNKK...........",
  ".........KNNNNNNNNNNK...........",
  ".........KNnNNNNNNnNK...........",
  ".........KNNNNNNNNNNK...........",
  "........KKNNNNNNNNNNKK..........",
  "........KNNnNNNNNNnNNK..........",
  "........KNNNNNNNNNNNNK..........",
  "........KKKKKKKKKKKKKK..........",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

const ALTAR_CANOPY: PixelMap = [
  "................................",
  "................................",
  "......KKKKKKKKKKKKKKKKKKKK......",
  ".....KCCCCCCCCCCCCCCCCCCCCK.....",
  "....KCCCTCCCTCCCTCCCTCCCTCCK....",
  "....KCCCCCCCCCCCCCCCCCCCCCCK....",
  "....KKKKKKKKKKKKKKKKKKKKKKKK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "....Kw....................wK....",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

const ALTAR_GOLD: PixelMap = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "...........GGGGGGGG.............",
  "................................",
  "................................",
  "................................",
  ".........GG........GG...........",
  "................................",
  "................................",
  "................................",
  "........GG..........GG..........",
  "................................",
  "........gGGGGGGGGGGGGg..........",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

const ALTAR_BIG_FLAME: PixelMap = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............f.................",
  ".............fFf................",
  ".............fFFf...............",
  "............fFFFFf..............",
  "............FFffFF..............",
  "...........FFffffFF.............",
  "...........FFffffFF.............",
  "............FFffFF..............",
  "............KFFFFK..............",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const ALTAR: PixelMap[] = [
  ALTAR_BASE,
  ALTAR_BASE,
  layer(ALTAR_BASE, ALTAR_CANOPY),
  layer(ALTAR_BASE, ALTAR_CANOPY, ALTAR_GOLD),
  layer(ALTAR_BASE, ALTAR_CANOPY, ALTAR_GOLD, ALTAR_BIG_FLAME),
];
