import type { PixelMap } from "./pixel";

/**
 * Terrain tiles and world props. Roles: G grass · g grass dark · h grass light ·
 * E highland grass · e highland dark · R rock · r rock dark · x rock light ·
 * k rock outline · B water · b water light · S shallow · s foam · D dirt ·
 * d dirt dark · W wood · w wood dark · T trunk · L leaf · l leaf dark ·
 * C canvas · c canvas shade · N stone · n stone dark · F fire · f fire bright ·
 * V violet · Y wheat · K outline
 */

export const GRASS_HI: PixelMap[] = [
  [
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEeEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEeEEEEEEEEEEEE",
    "EEEEEEEEEEEEEeEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEeEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEeEEEEEEEEEEEEE",
    "EEEEEEEEEEEeEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEeEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
  ],
  [
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEeEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEeEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEExEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEeEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EExEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
  ],
];

/** A cliff face — highland on top, sheer rock dropping to the south. */
export const CLIFF_FACE: PixelMap = [
  "EEEEEEEEEEEEEEEE",
  "EEEEEEEeEEEEEEEE",
  "kkkkkkkkkkkkkkkk",
  "RxRRRRRxRRRRRRxR",
  "RRRRrRRRRRRrRRRR",
  "RRRRRRRRRRRRRRRR",
  "rRRRRRRRRrRRRRRR",
  "RRRRRxRRRRRRRRRR",
  "RRRRRRRRRRRRRxRR",
  "RRrRRRRRRRRRRRRR",
  "RRRRRRRRRrRRRRRR",
  "RRRRRRRRRRRRRRRr",
  "rRRRRxRRRRRRRRRR",
  "RRRRRRRRRRRrRRRR",
  "RrRRRRRRRRRRRRRR",
  "kkkkkkkkkkkkkkkk",
];

/** A rocky rim for cliff tiles whose drop isn't to the south. */
export const CLIFF_RIM: PixelMap = [
  "kEEEEEEEEEEEEEEk",
  "kRRxRRRRRRRRxRRk",
  "kRRRRRRrRRRRRRRk",
  "kRrRRRRRRRRRRRRk",
  "kRRRRRRRRRRrRRRk",
  "kRRRRxRRRRRRRRRk",
  "kRRRRRRRRRRRRRRk",
  "kRRRRRRRRRxRRRRk",
  "kRrRRRRRRRRRRRRk",
  "kRRRRRRrRRRRRRRk",
  "kRRRRRRRRRRRRrRk",
  "kRRRxRRRRRRRRRRk",
  "kRRRRRRRRRRRRRRk",
  "kRRRRRRRRxRRRRRk",
  "kRRrRRRRRRRRRRRk",
  "kkkkkkkkkkkkkkkk",
];

/** A worn path cut into the cliff — walkable. */
export const RAMP: PixelMap = [
  "DDDDDDDDDDDDDDDD",
  "DdDDDDDrDDDDDDdD",
  "DDDDDDDDDDDDDDDD",
  "rrDDDDDDDDDDDDrr",
  "DDDDDdDDDDDDDDDD",
  "DDDDDDDDDDDrDDDD",
  "rDDDDDDDDDDDDDDr",
  "DDDDDDDDDDDDDDDD",
  "DDrDDDDDdDDDDDDD",
  "rrDDDDDDDDDDDDrr",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDrDDDDDDDDD",
  "rDDDDDDDDDDdDDDr",
  "DDDDDDDDDDDDDDDD",
  "DDDdDDDDDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
];

/** Fordable water — walkable. */
export const SHALLOW: PixelMap = [
  "SSSSSSSSSSSSSSSS",
  "SSsSSSSSSSSSSSSS",
  "SSSSSSSSSSaSSSSS",
  "SSSSSSSsSSSSSSSS",
  "SSSSSSSSSSSSSsSS",
  "SaSSSSSSSSSSSSSS",
  "SSSSSSSSSSSSSSSS",
  "SSSSSsSSSSSaSSSS",
  "SSSSSSSSSSSSSSSS",
  "SSSSSSSSSSSSSSSs",
  "SSSaSSSSsSSSSSSS",
  "SSSSSSSSSSSSSSSS",
  "SSSSSSSSSSSSaSSS",
  "SsSSSSSSSSSSSSSS",
  "SSSSSSSSsSSSSSSS",
  "SSSSSSSSSSSSSSSS",
];

/** Wooden footbridge tile, drawn over water. */
export const BRIDGE: PixelMap = [
  "wWWWWWWWWWWWWWWw",
  "wKKKKKKKKKKKKKKw",
  "WWWWWWWWWWWWWWWW",
  "WWWwWWWWWWWWwWWW",
  "KKKKKKKKKKKKKKKK",
  "WWWWWWWWWWWWWWWW",
  "WWWWWWWwWWWWWWWW",
  "KKKKKKKKKKKKKKKK",
  "WWWWWWWWWWWWWWWW",
  "WwWWWWWWWWWWWWwW",
  "KKKKKKKKKKKKKKKK",
  "WWWWWWWWWWWWWWWW",
  "WWWWWWWWWwWWWWWW",
  "KKKKKKKKKKKKKKKK",
  "wKKKKKKKKKKKKKKw",
  "wWWWWWWWWWWWWWWw",
];

/** 16×24 trees, origin bottom. */
export const TREES: PixelMap[] = [
  [
    "......KKKK......",
    "....KKLLLLKK....",
    "...KLLLLLLLLK...",
    "..KLLhLLLLLLLK..",
    "..KLLLLLLLLllK..",
    ".KLLLLLLLLLLLlK.",
    ".KLhLLLLLLLLllK.",
    ".KLLLLLLLLLlllK.",
    ".KLLLLLLLLLlllK.",
    "..KLLLLLLLlllK..",
    "..KlLLLLLLlllK..",
    "...KllLLLlllK...",
    "....KKllllKK....",
    "......KTTK......",
    "......KTTK......",
    "......KTTK......",
    "......KTTK......",
    ".....KTTTTK.....",
    "......KKKK......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  [
    ".......KK.......",
    "......KLLK......",
    ".....KLLLLK.....",
    ".....KLhLLK.....",
    "....KLLLLLlK....",
    "....KLLLLLlK....",
    "...KLLLLLLllK...",
    "...KLhLLLLllK...",
    "..KLLLLLLLlllK..",
    "..KLLLLLLLlllK..",
    ".KLLLLLLLLllllK.",
    ".KLLLLLLLlllllK.",
    "..KlLLLLLlllKK..",
    "...KKlLLlllK....",
    ".....KKllKK.....",
    "......KTTK......",
    "......KTTK......",
    "......KTTK......",
    ".....KTTTTK.....",
    "......KKKK......",
    "................",
    "................",
    "................",
    "................",
  ],
];

/** 16×12 boulder, origin bottom. */
export const ROCK: PixelMap = [
  "......kkkk......",
  "....kkxxRRkk....",
  "...kxxRRRRRRk...",
  "..kxRRRRRRRRrk..",
  "..kRRRRRRRRRrk..",
  ".kRRRRRRRRRrrrk.",
  ".kRRRRRRRRrrrrk.",
  ".kRrRRRRRrrrrrk.",
  "..krrrrrrrrrrk..",
  "...kkrrrrrrkk...",
  ".....kkkkkk.....",
  "................",
];

/** Shepherd's Camp: a tent and a small fire, 32×24, origin bottom. */
export const TENT: PixelMap = [
  ".........KK.....................",
  "........KCCK....................",
  ".......KCCCCK...................",
  "......KCCCCCcK..................",
  ".....KCCCCCCccK.................",
  "....KCCCCCCCcccK................",
  "...KCCCCCCCCccccK...............",
  "..KCCCCCCCCCcccccK..............",
  ".KCCCCCKKKCCccccccK.............",
  ".KCCCCKKKKKCcccccccK............",
  "KCCCCCKKKKKCcccccccK............",
  "KKKKKKKKKKKKKKKKKKKK............",
  ".........................f......",
  "........................fFf.....",
  ".......................fFFFf....",
  ".......................FFfFF....",
  "......................KFFFFFK...",
  "......................KKwwwKK...",
  ".....................KwwKKKwwK..",
  ".....................KKKKKKKKK..",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** Boatyard: stacked timber and a hull rib, 32×20, origin bottom. */
export const TIMBER: PixelMap = [
  "....................KK..........",
  "...................KwwK.........",
  "..................Kww..K........",
  ".................Kww....K.......",
  "................Kww......K......",
  "...............Kww........K.....",
  "..............KwwK........KK....",
  "..............KWWK..........K...",
  ".KKKKKKKKKKK..KWWK..........K...",
  "KWWWWWWWWWWWK.KWWK..........K...",
  "KwWWWWWWWWWwK.KKKK..........K...",
  "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
  ".KWWWWWWWWWWWWWWWWWWWWWWWWWWK...",
  ".KwWWWWWWWWWWWWWWWWWWWWWWWWwK...",
  ".KKKKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK.",
  "KwWWWWWWWWWWWWWWWWWWWWWWWWWWWwK.",
  "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
  "................................",
  "................................",
];

/** Standing Stones: three weathered monoliths, 32×36, origin bottom. */
export const STONES: PixelMap = [
  "............kkkkk...............",
  "...........kxxRRRk..............",
  "..........kxRRRRRRk.............",
  "..........kRRRRRRRk.............",
  "..........kRRRrRRRk.............",
  "..........kRRRRRRRk.............",
  "..........kRrRRRRRk......kkkk...",
  "..........kRRRRRrRk.....kxRRRk..",
  "...kkkk...kRRRRRRRk....kxRRRRRk.",
  "..kxRRRk..kRRRRRRRk....kRRRRRRk.",
  ".kxRRRRRk.kRRrRRRRk....kRRrRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRRrRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRRRRRRk.kRRRRRrRk....kRRRRrRk.",
  ".kRRRRRRk.kRrRRRRRk....kRRRRRRk.",
  ".kRRRRrRk.kRRRRRRRk....kRrRRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRrRRRRk.kRRRrRRRk....kRRRRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRrRRk.",
  ".kRRRrRRk.kRrRRRRRk....kRRRRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRrRRRRk.",
  ".kRRRRRRk.kRRRRRrRk....kRRRRRRk.",
  ".kRrRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".kRRRRrRk.kRRrRRRRk....kRRRrRRk.",
  ".kRRRRRRk.kRRRRRRRk....kRRRRRRk.",
  ".krrrrrrk.krrrrrrrk....krrrrrrk.",
  "kkkkkkkkkkkkkkkkkkkkk.kkkkkkkkkk",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** Milestone on the eastern road, 16×20, origin bottom. */
export const MILESTONE: PixelMap = [
  ".....KKKKKK.....",
  "....KNNNNNNK....",
  "....KNNNNNNK....",
  "....KNVNVNNK....",
  "....KNNNNNNK....",
  "....KNVVVNNK....",
  "....KNNNNNNK....",
  "....KNVNNNNK....",
  "....KNNNNNNK....",
  "....KNnNNnNK....",
  "....KNNNNNNK....",
  "....KNNNNNNK....",
  "....KnNNNNnK....",
  "...KNNNNNNNNK...",
  "...KnnnnnnnnK...",
  "...KKKKKKKKKK...",
  "................",
  "................",
  "................",
  "................",
];

/** Cave mouth set into a rock face, 32×24, origin bottom. */
export const CAVE: PixelMap = [
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
  "RRxRRRRRRRRRRRRRRRRRRRRRRRxRRRRR",
  "RRRRRRRRrRRRRRRRRRRRRrRRRRRRRRRR",
  "RRRRRRRRRRRkkkkkkkkkkRRRRRRRRRRR",
  "RRrRRRRRRkkKKKKKKKKKKkkRRRRRRrRR",
  "RRRRRRRRkKKKKKKKKKKKKKKkRRRRRRRR",
  "RRRRRRRkKKKKKKKKKKKKKKKKkRRRRRRR",
  "RRRRRRkKKKKKKKKKKKKKKKKKKkRRRRRR",
  "RxRRRRkKKKKKKKKKKKKKKKKKKkRRRRxR",
  "RRRRRkKKKKKKKKKKKKKKKKKKKKkRRRRR",
  "RRRRRkKKKKKKKKKKKKKKKKKKKKkRRRRR",
  "RRrRRkKKKKKKKKKKKKKKKKKKKKkRRrRR",
  "RRRRkKKKKKKKKKKKKKKKKKKKKKKkRRRR",
  "RRRRkKKKKKKKKKKKKKKKKKKKKKKkRRRR",
  "RRRRkKKKKKKKKKKKKKKKKKKKKKKkRRRR",
  "RRRRkKKKKKKKKKKKKKKKKKKKKKKkRRRR",
  "RRRRkKKKKKKKKKKKKKKKKKKKKKKkRRRR",
  "rrrrkKKKKKKKKKKKKKKKKKKKKKKkrrrr",
  "kkkkkKKKKKKKKKKKKKKKKKKKKKKkkkkk",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** The Ancient Olive — a huge gnarled tree, 32×36, origin bottom. */
export const OLIVE: PixelMap = [
  "..........KKKKKKKKKKK...........",
  "........KKLLLLLLLLLLLKK.........",
  "......KKLLLhLLLLLLLLLLLKK.......",
  ".....KLLLLLLLLLLLLLLLLllLK......",
  "....KLLhLLLLLLLLLLLLLLllllK.....",
  "...KLLLLLLLLLLLLLLLLLLlllllK....",
  "..KLLLLLLLLLLhLLLLLLLLllllllK...",
  "..KLLhLLLLLLLLLLLLLLLLllllllK...",
  ".KLLLLLLLLLLLLLLLLLLLLlllllllK..",
  ".KLLLLLLLLhLLLLLLLLLLllllllllK..",
  ".KLLLLLLLLLLLLLLLLLLLllllllllK..",
  ".KLLhLLLLLLLLLLLhLLLLllllllllK..",
  ".KLLLLLLLLLLLLLLLLLLlllllllllK..",
  "..KLLLLLLLLLLLLLLLLLllllllllK...",
  "..KlLLLLLLLLLLLLLLLlllllllllK...",
  "...KlLLLLLLLLLLLLLllllllllKK....",
  "....KKlLLLLLLLLLllllllllKK......",
  "......KKllLLLLllllllllKK........",
  "........KKKllllllKKKK...........",
  "...........KTTTTK...............",
  "...........KTTTTK...............",
  "..........KTTTTTTK..............",
  "..........KTTTTTTK..............",
  "..........KTTKTTTK..............",
  ".........KTTTKKTTTK.............",
  ".........KTTTK.KTTK.............",
  "........KTTTTK.KTTTK............",
  "........KTTTK...KTTK............",
  ".......KTTTTK...KTTTK...........",
  ".......KKKKK.....KKKK...........",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** Broken Cistern: a cracked stone ring holding dark water, 32×20, origin bottom. */
export const CISTERN: PixelMap = [
  "..........KKKKKKKKKK............",
  "........KKNNNNNNNNNNKK..........",
  "......KKNNnNNNNNNNNnNNKK........",
  ".....KNNNNKKKKKKKKKKNNNNK.......",
  "....KNnNKKBBBBBBBBBBKKNnNK......",
  "....KNNNKBBBbBBBBBBBBKNNNK......",
  "...KNNNKBBBBBBBBBbBBBBKNNNK.....",
  "...KNnNKBBBBBBBBBBBBBBKNnNK.....",
  "...KNNNKBbBBBBBBBBBBBBKNNNK.....",
  "...KNNNNKBBBBBBBBbBBBKNNNNK.....",
  "....KNnNNKBBBBBBBBBBKNNnNK......",
  "....KNNNNNKKKKKKKKKKNNNNNK......",
  ".....KNNNNNNNN..NNNNNNNNK.......",
  "......KKnnnNNN..NNNnnnKK........",
  "........KKKKKK.KKKKKK...........",
  "..kk...........................k",
  ".kRRk.......................kkRk",
  ".krrk......................kRRrk",
  "..kk.......................kkkk.",
  "................................",
];

/** Granary: Noah's storehouse — stone base, timber loft, 32×32 (2×2 tiles), origin bottom. */
export const GRANARY: PixelMap = [
  "...............KK...............",
  ".............KKWWKK.............",
  "...........KKWWWWWWKK...........",
  ".........KKWWWWWWWWWWKK.........",
  ".......KKWWWWwWWWWWWWWWKK.......",
  ".....KKWWWWWWwwWWWWWWWWWWKK.....",
  "...KKWWWWWWWWwwWWWWWWWWWWWWKK...",
  ".KKWWWWWWWWWWwwwWWWWWWWWWWWWWKK.",
  ".KwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.",
  ".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
  "..KWWWWWWWWWWWWWWWWWWWWWWWWWWK..",
  "..KWwWWWWWWWWWWWWWWWWWWWWWwWWK..",
  "..KWWWWKKKKKKWWWWWWKKKKKKWWWWK..",
  "..KWWWWKYYYYKWWWWWWKYYYYKWWWWK..",
  "..KWWWWKYYYYKWWWWWWKYYYYKWWWWK..",
  "..KWWWWKKKKKKWWWWWWKKKKKKWWWWK..",
  "..KWWWWWWWWWWWWWWWWWWWWWWWWWWK..",
  "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
  "..KNNNNNNNNNNNNKKKKNNNNNNNNNNK..",
  "..KNnNNNNNNNNNKwwwwKNNNNNNNnNK..",
  "..KNNNNNNNNNNNKwwwwKNNNNNNNNNK..",
  "..KNNNNNNNNNNNKwwwwKNNNNNNNNNK..",
  "..KNnNNNNNNNNNKwwwwKNNNNNNNnNK..",
  "..KNNNNKYYKNNNKwwwwKNNNKYYKNNK..",
  "..KNNNKYYYYKNNKwwwwKNNKYYYYKNK..",
  "..KNNNKYYYYKNNKwwwwKNNKYYYYKNK..",
  "..KnnnKKKKKKnnKwwwwKnnKKKKKKnK..",
  "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
  "................................",
  "................................",
  "................................",
  "................................",
];

/** Beacon: a stone pillar with a caged fire, 16×32, origin bottom. */
export const BEACON: PixelMap = [
  "......ff........",
  ".....fFFf.......",
  "....fFFFFf......",
  "....FFffFF......",
  "...FFffffFF.....",
  "...FFffffFF.....",
  "....FFffFF......",
  "...KKFFFFKK.....",
  "...K.KFFK.K.....",
  "...K.KKKK.K.....",
  "...KKKKKKKK.....",
  "....KNNNNK......",
  "....KNnNNK......",
  "....KNNNNK......",
  "....KNNnNK......",
  "....KNNNNK......",
  "....KnNNNK......",
  "....KNNNNK......",
  "....KNNnNK......",
  "....KNNNNK......",
  "....KNnNNK......",
  "....KNNNNK......",
  "....KNNNNK......",
  "...KNNNNNNK.....",
  "...KNnNNNnK.....",
  "..KNNNNNNNNK....",
  "..KnnnnnnnnK....",
  "..KKKKKKKKKK....",
  "................",
  "................",
  "................",
  "................",
];

/** Quest marker "!" — tinted at runtime for state. 8×12. */
export const MARKER: PixelMap = [
  "..KKKK..",
  ".KGGGGK.",
  ".KGGGGK.",
  ".KGGGGK.",
  "..KGGK..",
  "..KGGK..",
  "..KGGK..",
  "...KK...",
  "..KKKK..",
  ".KGGGGK.",
  ".KGGGGK.",
  "..KKKK..",
];
